### ISSUE TITLE
Links in the Events List forward to a local webpage

### ISSUE THREAD

**Issue by khaled196** [ElixirTeSS/TeSS_widgets#38]
Hi, 

I have an issue using the Tess Widget API, as the links from the events are forwarded to an internal page on my website. 

I just copied the code for the Tess Widgets from https://elixirtess.github.io/TeSS_widgets/ 

```
<link rel="stylesheet" property="stylesheet" href="https://elixirtess.github.io/TeSS_widgets/css/tess-widget.css"/>
<div id="tess-widget-events-list" class="tess-widget tess-widget-list"></div>
<script>
function initTeSSWidgets() {
    TessWidget.Events(document.getElementById('tess-widget-events-list'),
        'SimpleList',
        {
            params: {
                pageSize: 5,
                country: ['Belgium']
            }
        });
}
</script>
<script async="" defer="" src="https://elixirtess.github.io/TeSS_widgets/js/tess-widget-standalone.js" onload="initTeSSWidgets()"></script>
```

The links in the Tess Widgets are working for the materials list, but not for the events. Can you please help with that?

**Comment by poterlowicz-lab** [comment]
@fbacall would you be able to help

**Comment by fbacall** [comment]
Hi @khaled196 and @poterlowicz-lab 

Apologies for this, it was not building the URL correctly. It should be fixed now (you may need to hard refresh using Ctrl+F5 to get the fixed code).

**Comment by khaled196** [comment]
Thank you @fbacall
